#!/usr/bin/env bash

test_name="$1"
shift 1

if [ -z "$test_name" ]; then
    >&2 "error: no test name"
    exit 1
fi

set -eo pipefail # pipefail must be set manually again
trap 'echo "## FAILED: $test_name"' ERR

echo "## START: $test_name"

export FM_TEST_NAME="$test_name"

# Note: before we fixed port allocation we run in different namespaces like this:
# unshare -rn bash -c "ip link set lo up && exec unshare --user $*" 2>&1 | ts -s
"$@" 2>&1 | ts -s

echo "## COMPLETE: $test_name"
