pub const FM_DISABLE_META_MODULE_ENV: &str = "FM_DISABLE_META_MODULE";

pub const FM_DATA_DIR_ENV: &str = "FM_DATA_DIR";

pub const FM_BIND_TOKIO_CONSOLE_ENV: &str = "FM_BIND_TOKIO_CONSOLE";

pub const FM_BIND_P2P_ENV: &str = "FM_BIND_P2P";

pub const FM_P2P_URL_ENV: &str = "FM_P2P_URL";

pub const FM_BIND_API_ENV: &str = "FM_BIND_API";

pub const FM_API_URL_ENV: &str = "FM_API_URL";

pub const FM_BIND_UI_ENV: &str = "FM_BIND_UI";

pub const FM_BITCOIN_NETWORK_ENV: &str = "FM_BITCOIN_NETWORK";

pub const FM_BIND_METRCIS_ENV: &str = "FM_BIND_METRICS";

pub const FM_PORT_ESPLORA_ENV: &str = "FM_PORT_ESPLORA";

pub const FM_FORCE_API_SECRETS_ENV: &str = "FM_FORCE_API_SECRETS";

pub const FM_BITCOIND_URL_ENV: &str = "FM_BITCOIND_URL";

pub const FM_BITCOIND_URL_PASSWORD_FILE_ENV: &str = "FM_BITCOIND_URL_PASSWORD_FILE";

pub const FM_ESPLORA_URL_ENV: &str = "FM_ESPLORA_URL";

pub const FM_ENABLE_IROH_ENV: &str = "FM_ENABLE_IROH";

pub const FM_DB_CHECKPOINT_RETENTION_ENV: &str = "FM_DB_CHECKPOINT_RETENTION";
