# The contents of this file are appended to the ~/.bashrc file within the docker image.
#
# `nix develop` sourcs .bashrc. Looping is avoided using an enviroment flag.
if [[ -z $NIX_DEVELOP_ACTIVE ]]; then
  # Enviroment variable was undefined. Therefore, define and call nix.
  NIX_DEVELOP_ACTIVE=1
else
  # Enviroment variable was already defined, avoid calling nix.
  NIX_DEVELOP_ACTIVE=0
fi
if [ $NIX_DEVELOP_ACTIVE == 1 ]
then
    echo "Activating nix develop."
    NIX_DEVELOP_ACTIVE=0 nix develop --extra-experimental-features nix-command --extra-experimental-features flakes;
fi
