(function() {var implementors = {
"fedimint_dummy_common":[["impl <a class=\"trait\" href=\"fedimint_core/core/trait.Input.html\" title=\"trait fedimint_core::core::Input\">Input</a> for <a class=\"struct\" href=\"fedimint_dummy_common/struct.DummyInput.html\" title=\"struct fedimint_dummy_common::DummyInput\">DummyInput</a>"]],
"fedimint_empty_common":[["impl <a class=\"trait\" href=\"fedimint_core/core/trait.Input.html\" title=\"trait fedimint_core::core::Input\">Input</a> for <a class=\"struct\" href=\"fedimint_empty_common/struct.EmptyInput.html\" title=\"struct fedimint_empty_common::EmptyInput\">EmptyInput</a>"]],
"fedimint_ln_common":[["impl <a class=\"trait\" href=\"fedimint_core/core/trait.Input.html\" title=\"trait fedimint_core::core::Input\">Input</a> for <a class=\"enum\" href=\"fedimint_ln_common/enum.LightningInput.html\" title=\"enum fedimint_ln_common::LightningInput\">LightningInput</a>"]],
"fedimint_lnv2_common":[["impl <a class=\"trait\" href=\"fedimint_core/core/trait.Input.html\" title=\"trait fedimint_core::core::Input\">Input</a> for <a class=\"enum\" href=\"fedimint_lnv2_common/enum.LightningInput.html\" title=\"enum fedimint_lnv2_common::LightningInput\">LightningInput</a>"]],
"fedimint_meta_common":[["impl <a class=\"trait\" href=\"fedimint_core/core/trait.Input.html\" title=\"trait fedimint_core::core::Input\">Input</a> for <a class=\"struct\" href=\"fedimint_meta_common/struct.MetaInput.html\" title=\"struct fedimint_meta_common::MetaInput\">MetaInput</a>"]],
"fedimint_mint_common":[["impl <a class=\"trait\" href=\"fedimint_core/core/trait.Input.html\" title=\"trait fedimint_core::core::Input\">Input</a> for <a class=\"enum\" href=\"fedimint_mint_common/enum.MintInput.html\" title=\"enum fedimint_mint_common::MintInput\">MintInput</a>"]],
"fedimint_unknown_common":[["impl <a class=\"trait\" href=\"fedimint_core/core/trait.Input.html\" title=\"trait fedimint_core::core::Input\">Input</a> for <a class=\"struct\" href=\"fedimint_unknown_common/struct.UnknownInput.html\" title=\"struct fedimint_unknown_common::UnknownInput\">UnknownInput</a>"]],
"fedimint_wallet_common":[["impl <a class=\"trait\" href=\"fedimint_core/core/trait.Input.html\" title=\"trait fedimint_core::core::Input\">Input</a> for <a class=\"enum\" href=\"fedimint_wallet_common/enum.WalletInput.html\" title=\"enum fedimint_wallet_common::WalletInput\">WalletInput</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()