// Env variable to TODO
pub const FM_ROCKSDB_WRITE_BUFFER_SIZE_ENV: &str = "FM_ROCKSDB_WRITE_BUFFER_SIZE";
pub const FM_ROCKSDB_BLOCK_CACHE_SIZE_ENV: &str = "FM_ROCKSDB_BLOCK_CACHE_SIZE";
pub const FM_ROCKSDB_WAL_SYNC_INTERVAL_MS: &str = "FM_ROCKSDB_WAL_SYNC_INTERVAL_MS";
