#!/usr/bin/env bash

set -eo pipefail

test_name="$1"
shift 1

if [ -z "$test_name" ]; then
    >&2 "error: no test name"
    exit 1
fi

version_str="${FM_RUN_TEST_VERSIONS:+ ($FM_RUN_TEST_VERSIONS)}"
test_out_path="$(mktemp --tmpdir fm-XXXXX)"
time_out_path="$(mktemp --tmpdir fm-XXXXX)"
time_fmt='%e\t%M\t%w\t%c'

export FM_TEST_NAME="$test_name"
TMPDIR="$(mktemp -d --tmpdir "fm-${FM_TEST_NAME:0:12}-XXXX")"
FM_RUN_TEST_TMPDIR="$TMPDIR"

echo "## RUN:  $test_name$version_str"

on_error() {
  echo "## OUT:  $test_name$version_str"
  cat "$test_out_path"
  echo "## FAIL: $test_name$version_str"
  echo "## LOG FEDIMINTD-0:"
  cat "$FM_RUN_TEST_TMPDIR/logs/fedimintd-default-0.log"
  echo "## LOG LND GATEWAY:"
  cat "$FM_RUN_TEST_TMPDIR/logs/gatewayd-lnd.log"
  echo "## LOG LDK-0 GATEWAY:"
  cat "$FM_RUN_TEST_TMPDIR/logs/gatewayd-ldk-0.log"
  echo "## END."
}

on_exit() {
    exit_status=$?
    if [ $exit_status -eq 0 ]; then
        # if successful, don't waste space keeping the test dir
        rm -Rf "$FM_RUN_TEST_TMPDIR"
    fi
}
trap on_error ERR
trap on_exit EXIT

FM_RUN_TEST_TIMEOUT_SOFT=${FM_RUN_TEST_TIMEOUT:-310}

command time -q --format="$time_fmt" -o "$time_out_path" \
    timeout -k 10 "$FM_RUN_TEST_TIMEOUT_SOFT" \
    "$@" 2>&1 | ts -i "%.S" | ts -s "%M:%S" > "$test_out_path"

awk 'BEGIN {FS="\t"} {printf "## STAT: %8.2fs %8dB %8dW %8dc\n", $1, $2, $3, $4}' < "$time_out_path"
echo "## DONE: $test_name$version_str"
