on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

name: Crate ownership check

permissions:
  contents: read

jobs:
  check-ownership:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/pin-nix-flake-inputs
      - name: Check crates.io ownership
        run: |
          nix develop -c ./scripts/ci/check-crate-ownership.sh

  notifications:
    if: always() && github.repository == 'fedimint/fedimint'
    name: "Notifications"
    timeout-minutes: 1
    runs-on: [self-hosted, linux, x64]
    needs: [ check-ownership ]

    steps:
    - name: Discord notifications on failure
      if: ${{ always() && contains(needs.*.result, 'failure') }}
      uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: failure
