on:
  schedule:
    - cron:  '30 * * * *' # every hour at `x:30`
  workflow_dispatch:

name: Hourly check

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  self-care:
    name: Flake self-check
    # no one is in the rush for this to funish, so use default (free) Ubuntu instances
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
        with:
          fail-mode: true
          nixpkgs-keys: nixpkgs

  test:
    if: github.repository == 'fedimint/fedimint'
    strategy:
      matrix:
        host:
          - linux
        include:
          - host: linux
            # no one is in the rush for this to funish, so use default (free) Ubuntu instances
            runs-on: [self-hosted, linux, x64]
            timeout: 75
            run-tests: true

    name: "Test on ${{ matrix.host }}"
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: ${{ matrix.timeout }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: dpc/nix-installer-action@c6e05d595d5ed6d6b7c46e42409ca2a126efe13d # dpc/jj-vqymqvyntouw

      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: fedimint
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        continue-on-error: true
      - uses: ./.github/actions/pin-nix-flake-inputs

      - name: Tests (5 times more)
        run: |
          set -euo pipefail
          # first one might do nothing
          nix build -L .#wasm32-unknown.ci.ciTestAll
          # but this one will run
          nix build -L .#wasm32-unknown.ci.ciTestAll --rebuild

      - name: Wasm Tests
        run: |
          set -euo pipefail
          nix build -L .#wasm32-unknown.ci.wasmTest
          nix build -L .#wasm32-unknown.ci.wasmTest --rebuild


  notifications:
    if: always() && github.repository == 'fedimint/fedimint' && github.event_name != 'merge_group'
    name: "Notifications"
    timeout-minutes: 1
    runs-on: [self-hosted, linux, x64]
    # note: we don't depend on `audit` because it will
    # be often broken, and we can't fix it immediately
    needs: [ test ]

    steps:
    - name: Discord notifications on failure
      # https://stackoverflow.com/a/74562058/134409
      if: ${{ always() && contains(needs.*.result, 'failure') }}
      # https://github.com/marketplace/actions/actions-status-discord
      uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        # current job is a success, but that's not what we're interested in
        status: failure
