on: [push, pull_request]

name: Markdown Link Check

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: [self-hosted, linux, x64]
    continue-on-error: true # can fail for external reasons, so don't be a blocker
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Persist lychee cache, so we don't bother with checking same links all the time
      # Should also minimize number of flakes.
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - uses: ./.github/actions/pin-nix-flake-inputs

      # Accept 429 status codes so we don't fail when GitHub rate-limits us. The --github-token option didn't work and
      # this way we'll successfully check *some* links each run, cache them and check others the next run.
      - name: Check links
        run: |
          nix develop .#linkcheck -c lychee \
            --verbose \
            --cache \
            --cache-exclude-status "429" \
            --accept "200, 429" \
            docs README.md
