name: 'create reminder'

permissions:
  issues: write
  pull-requests: write

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: 👀 check for reminder
        uses: agrc/create-reminder-action@8798362d131d74a70435283581f566c4986328dd # v1.1.25
