name: 'create reminder'

permissions:
  issues: write
  pull-requests: write

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: 👀 check for reminder
        uses: agrc/create-reminder-action@c2025868f56a49dfc239012c78cb8e2beee5554e # v1.1.26
